rejester:
  registry_addresses: [ "redis.example.com:6379" ]
  namespace: test

kvlayer:
  app_name: kba
  namespace: test
  storage_type: accumulo
  storage_addresses: [ "test-accumulo-1.example.com:50096" ]
  username: root
  password: secret

elasticsearch:
  cluster:
     - host: "testcluster"
       port: 9200


streamcorpus_pipeline:
  root_path: 

  tmp_dir_path: tmp
  cleanup_tmp_files: true

  reader: from_s3_chunks

  batch_transforms: []

  writers: 
    - elasticsearch_writer

  from_s3_chunks:
    aws_access_key_id_path:     /data/trec-kba/keys/trec-aws-s3.aws_access_key_id
    aws_secret_access_key_path: /data/trec-kba/keys/trec-aws-s3.aws_secret_access_key
    bucket: aws-publicdatasets
    s3_path_prefix: trec/kba/kba-streamcorpus-2014-v0_3_0
    tries: 10
    input_format: streamitem
    streamcorpus_version: v0_3_0
    gpg_decryption_key_path: /data/trec-kba/keys/trec-kba-rsa.gpg-key.private

  elasticsearch_writer:
    index_name: "stream-items-index"
